### ISSUE TITLE
SAPI拡張のインストールに失敗する

### ISSUE THREAD

**Issue by riku22** [actlaboratory/HISS-releases#39]
こんにちは。

問題の報告がこちらでよいのか分からないのですが、報告です。

先ほど、HISS を 1.3.2 に更新しました。
その後、SAPI拡張機能を実行して「インストール」ボタンを押してインストールしようとすると、下記のようなライセンスファイルがない旨のエラーが表示され、インストールに失敗してしまいます。

```
インストールに失敗しました。
C:\Users\riku\AppData\Roaming\nvda\addons\HISS\HISS-license1.dat が見つかりません。
```

再現しますでしょうか。
もし可能でしたら、修正いただけると助かります。

よろしくお願いいたします。

**Comment by yncat** [comment]
再現しましたが、原因はまだ分かっていないので調査します。
ファイルを探すディレクトリが1段下に下がってしまったようですが、なんでそうなったのかよくわかりません。

**Comment by yncat** [comment]
PyInstaller の更新で `__file__` が返すパスが1段下になっていました。修正できそうです。ご不便おかけしました。

**Comment by yncat** [comment]
version 1.3.3 をリリースして修正しました。ご確認お願いします！

**Comment by riku22** [comment]
1.3.3 での修正を確認しました。
ありがとうございました！
